name: EasyBan
version: 1.6
main: org.example.easyban.EasyBan
api-version: 1.21
author: VovchikCraft
commands:
  eb:
    description: Main command for EasyBan
    usage: /eb <args>
    permission: easyban.use
permissions:
  easyban.use:
    description: Allows use of ban commands
    default: op